services:
  postgres:
    image: postgres:16-alpine
    container_name: catalogo-palavras-db
    restart: unless-stopped
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB_HOST=${DB_HOST}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
