services:
  postgres:
    image: postgres:16-alpine
    container_name: catalogo-palavras-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: catalogo
      POSTGRES_PASSWORD: catalogo123
      POSTGRES_DB: catalogo_palavras
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
